name: "sbom.sh-create"
description: "SBOM.sh - Generate and upload SBOM to sbom.sh using Trivy, Syft, or Grype"
inputs:
  scan_type:
    description: 'Type of scan (trivyfs, trivyimage, grypefs, grypeimage, syftfs, syftimage)'
    required: true
    default: 'trivyfs'
  target:
    description: 'Scan target (applicable for image scans)'
    required: false
    default: ''
runs:
  using: 'docker'
  image: 'docker://codenotary/sbom.sh:latest'
  args:
    - ${{ inputs.scan_type }}
    - ${{ inputs.target }}